// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aclrxmmzswbryahjauya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbHJ4bW16c3dicnlhaGphdXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjE1MzksImV4cCI6MjA3MTI5NzUzOX0.z_RtXx20NQGrflxCEQlBdGN-n3oh6XeJx-cQ0sNFQBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});